const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function main() {
  // ─── Clean ────────────────────────────────────────────────────────────────
  await prisma.like.deleteMany();
  await prisma.follow.deleteMany();
  await prisma.comment.deleteMany();
  await prisma.post.deleteMany();
  await prisma.user.deleteMany();

  // ─── Users (100) ─────────────────────────────────────────────────────────
  const userData = [
    { username: "liam_smith",       email: "liam.smith@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=1",   bio: "Coffee lover and amateur photographer." },
    { username: "noah_johnson",     email: "noah.johnson@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=2",   bio: "Building things one line of code at a time." },
    { username: "oliver_williams",  email: "oliver.williams@orbit.app",  password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=3",   bio: "Traveler | Foodie | Dreamer." },
    { username: "elijah_brown",     email: "elijah.brown@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=4",   bio: "Living life to the fullest every day." },
    { username: "james_jones",      email: "james.jones@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=5",   bio: "Designer by day, gamer by night." },
    { username: "aiden_garcia",     email: "aiden.garcia@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=6",   bio: "Books, tea, and long walks on the beach." },
    { username: "lucas_miller",     email: "lucas.miller@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=7",   bio: "Passionate about technology and innovation." },
    { username: "mason_davis",      email: "mason.davis@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=8",   bio: "Fitness enthusiast and healthy living advocate." },
    { username: "ethan_wilson",     email: "ethan.wilson@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=9",   bio: "Music is my therapy." },
    { username: "logan_anderson",   email: "logan.anderson@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=10",  bio: "Exploring the world one city at a time." },
    { username: "emma_taylor",      email: "emma.taylor@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=11",  bio: "Software engineer | Open source contributor." },
    { username: "olivia_thomas",    email: "olivia.thomas@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=12",  bio: "Artist and storyteller." },
    { username: "ava_jackson",      email: "ava.jackson@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=13",  bio: "Nature lover and outdoor adventurer." },
    { username: "isabella_white",   email: "isabella.white@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=14",  bio: "Entrepreneur | Startup enthusiast." },
    { username: "sophia_harris",    email: "sophia.harris@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=15",  bio: "Cat mom | Plant parent | Coffee addict." },
    { username: "mia_martin",       email: "mia.martin@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=16",  bio: "Just here to share good vibes." },
    { username: "charlotte_thompson", email: "charlotte.thompson@orbit.app", password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=17", bio: "Learning something new every single day." },
    { username: "amelia_young",     email: "amelia.young@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=18",  bio: "Food blogger and recipe creator." },
    { username: "harper_allen",     email: "harper.allen@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=19",  bio: "Frontend dev who loves clean UI." },
    { username: "evelyn_king",      email: "evelyn.king@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=20",  bio: "Making the internet a better place." },
    { username: "benjamin_scott",   email: "benjamin.scott@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=21",  bio: "Bookworm and coffee enthusiast." },
    { username: "alexander_green",  email: "alexander.green@orbit.app",  password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=22",  bio: "Full-stack developer and open-source advocate." },
    { username: "henry_baker",      email: "henry.baker@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=23",  bio: "Hiking trails and mountain views." },
    { username: "sebastian_adams",  email: "sebastian.adams@orbit.app",  password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=24",  bio: "Minimalist. Thinker. Builder." },
    { username: "jackson_nelson",   email: "jackson.nelson@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=25",  bio: "Amateur chef and food lover." },
    { username: "amir_hill",        email: "amir.hill@orbit.app",        password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=26",  bio: "Passionate about AI and machine learning." },
    { username: "zaid_carter",      email: "zaid.carter@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=27",  bio: "Startup founder. Dreamer." },
    { username: "yusuf_mitchell",   email: "yusuf.mitchell@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=28",  bio: "Photography and long drives." },
    { username: "omar_perez",       email: "omar.perez@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=29",  bio: "Gaming | Music | Code." },
    { username: "khalid_roberts",   email: "khalid.roberts@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=30",  bio: "Spreading positivity one post at a time." },
    { username: "sara_turner",      email: "sara.turner@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=31",  bio: "Yoga, meditation, and green tea." },
    { username: "nour_phillips",    email: "nour.phillips@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=32",  bio: "Interior design enthusiast." },
    { username: "layla_campbell",   email: "layla.campbell@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=33",  bio: "Wanderlust and wandering feet." },
    { username: "fatima_parker",    email: "fatima.parker@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=34",  bio: "Science communicator and educator." },
    { username: "hana_evans",       email: "hana.evans@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=35",  bio: "Illustrator and comic strip creator." },
    { username: "rania_edwards",    email: "rania.edwards@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=36",  bio: "Nurse by profession, writer by heart." },
    { username: "dina_collins",     email: "dina.collins@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=37",  bio: "Chasing sunsets and good coffee." },
    { username: "yasmin_stewart",   email: "yasmin.stewart@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=38",  bio: "Poet and short-story writer." },
    { username: "tariq_sanchez",    email: "tariq.sanchez@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=39",  bio: "DevOps engineer who loves automation." },
    { username: "faris_morris",     email: "faris.morris@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=40",  bio: "Cyclist and outdoor sports fan." },
    { username: "carlos_rogers",    email: "carlos.rogers@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=41",  bio: "Musician and band member." },
    { username: "miguel_reed",      email: "miguel.reed@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=42",  bio: "Architecture student with big dreams." },
    { username: "sofia_cook",       email: "sofia.cook@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=43",  bio: "Digital marketer and content creator." },
    { username: "valentina_morgan", email: "valentina.morgan@orbit.app", password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=44",  bio: "Sustainable living advocate." },
    { username: "diego_bell",       email: "diego.bell@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=45",  bio: "Basketball fan and weekend player." },
    { username: "mateo_murphy",     email: "mateo.murphy@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=46",  bio: "UX designer and usability nerd." },
    { username: "camila_bailey",    email: "camila.bailey@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=47",  bio: "Mental health advocate and listener." },
    { username: "lucia_rivera",     email: "lucia.rivera@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=48",  bio: "Language learner — currently on Spanish." },
    { username: "ana_cooper",       email: "ana.cooper@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=49",  bio: "Biochemistry PhD student." },
    { username: "chen_wei",         email: "chen.wei@orbit.app",         password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=50",  bio: "Data scientist and chess player." },
    { username: "wei_zhang",        email: "wei.zhang@orbit.app",        password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=51",  bio: "Backend engineer. Coffee before code." },
    { username: "mei_liu",          email: "mei.liu@orbit.app",          password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=52",  bio: "Graphic designer and typography lover." },
    { username: "jun_wang",         email: "jun.wang@orbit.app",         password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=53",  bio: "Competitive programmer." },
    { username: "xiao_chen",        email: "xiao.chen@orbit.app",        password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=54",  bio: "Blockchain and Web3 explorer." },
    { username: "yuki_tanaka",      email: "yuki.tanaka@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=55",  bio: "Anime fan and manga reader." },
    { username: "kenji_sato",       email: "kenji.sato@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=56",  bio: "Software architect and mentor." },
    { username: "sakura_ito",       email: "sakura.ito@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=57",  bio: "Florist and nature enthusiast." },
    { username: "hiro_yamamoto",    email: "hiro.yamamoto@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=58",  bio: "Robotics engineer." },
    { username: "rin_kobayashi",    email: "rin.kobayashi@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=59",  bio: "Calligraphy artist and tea ceremony practitioner." },
    { username: "priya_patel",      email: "priya.patel@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=60",  bio: "Fintech product manager." },
    { username: "arjun_kumar",      email: "arjun.kumar@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=61",  bio: "Startup co-founder. Chai addict." },
    { username: "neha_singh",       email: "neha.singh@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=62",  bio: "Data analyst and dashboard queen." },
    { username: "rahul_sharma",     email: "rahul.sharma@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=63",  bio: "Mobile developer | Flutter fan." },
    { username: "ananya_gupta",     email: "ananya.gupta@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=64",  bio: "Social entrepreneur and NGO volunteer." },
    { username: "vikram_mehta",     email: "vikram.mehta@orbit.app",     password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=65",  bio: "Cloud architect and AWS certified." },
    { username: "kavya_reddy",      email: "kavya.reddy@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=66",  bio: "Cybersecurity analyst." },
    { username: "rohan_verma",      email: "rohan.verma@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=67",  bio: "Game developer and Unity enthusiast." },
    { username: "shreya_nair",      email: "shreya.nair@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=68",  bio: "Journalist and podcast host." },
    { username: "ivan_petrov",      email: "ivan.petrov@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=69",  bio: "Systems programmer and Rust evangelist." },
    { username: "elena_ivanova",    email: "elena.ivanova@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=70",  bio: "Ballet dancer and choreographer." },
    { username: "dmitri_sokolov",   email: "dmitri.sokolov@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=71",  bio: "Mathematician and puzzle enthusiast." },
    { username: "natasha_volkova",  email: "natasha.volkova@orbit.app",  password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=72",  bio: "Linguist studying five languages." },
    { username: "alexei_morozov",   email: "alexei.morozov@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=73",  bio: "Space enthusiast and astronomy hobbyist." },
    { username: "olga_kuznetsova",  email: "olga.kuznetsova@orbit.app",  password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=74",  bio: "Pediatric nurse and mother of two." },
    { username: "sergei_lebedev",   email: "sergei.lebedev@orbit.app",   password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=75",  bio: "Astrophysics researcher." },
    { username: "vera_popova",      email: "vera.popova@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=76",  bio: "Vintage fashion collector." },
    { username: "felix_mueller",    email: "felix.mueller@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=77",  bio: "Embedded systems engineer." },
    { username: "clara_schneider",  email: "clara.schneider@orbit.app",  password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=78",  bio: "Environmental activist and vegan chef." },
    { username: "max_fischer",      email: "max.fischer@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=79",  bio: "Photographer and videographer." },
    { username: "lea_weber",        email: "lea.weber@orbit.app",        password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=80",  bio: "UX researcher and accessibility advocate." },
    { username: "jonas_meyer",      email: "jonas.meyer@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=81",  bio: "Backend dev who loves databases." },
    { username: "nina_hoffmann",    email: "nina.hoffmann@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=82",  bio: "Actress and theatre director." },
    { username: "leon_wagner",      email: "leon.wagner@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=83",  bio: "Competitive swimmer." },
    { username: "anna_becker",      email: "anna.becker@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=84",  bio: "Clinical psychologist and researcher." },
    { username: "tom_harris",       email: "tom.harris@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=85",  bio: "Crypto trader and DeFi explorer." },
    { username: "grace_clark",      email: "grace.clark@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=86",  bio: "Librarian and book club organizer." },
    { username: "jack_lewis",       email: "jack.lewis@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=87",  bio: "IoT engineer and maker space regular." },
    { username: "lily_robinson",    email: "lily.robinson@orbit.app",    password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=88",  bio: "Dietitian and wellness coach." },
    { username: "sam_walker",       email: "sam.walker@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=89",  bio: "DevRel engineer and community builder." },
    { username: "zoe_hall",         email: "zoe.hall@orbit.app",         password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=90",  bio: "Motion graphics designer." },
    { username: "ryan_allen",       email: "ryan.allen@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=91",  bio: "Sports journalist and podcaster." },
    { username: "chloe_young",      email: "chloe.young@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=92",  bio: "Fashion blogger and stylist." },
    { username: "tyler_king",       email: "tyler.king@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=93",  bio: "Ethical hacker and CTF player." },
    { username: "ava_wright",       email: "ava.wright@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=94",  bio: "Quantum computing researcher." },
    { username: "ethan_lopez",      email: "ethan.lopez@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=95",  bio: "Mechanical engineer turned software dev." },
    { username: "maya_hill",        email: "maya.hill@orbit.app",        password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=96",  bio: "Marine biologist and ocean conservationist." },
    { username: "dylan_scott",      email: "dylan.scott@orbit.app",      password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=97",  bio: "Indie game dev and pixel artist." },
    { username: "nora_green",       email: "nora.green@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=98",  bio: "Legal tech enthusiast." },
    { username: "jake_adams",       email: "jake.adams@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=99",  bio: "Urban photographer and street art lover." },
    { username: "ruby_baker",       email: "ruby.baker@orbit.app",       password: "password123", role: "USER", profilePicture: "https://i.pravatar.cc/150?u=100", bio: "Biotech startup founder." },
  ];

  const users = [];
  for (const data of userData) {
    const user = await prisma.user.create({ data });
    users.push(user);
  }
  console.log(`Created ${users.length} users.`);

  // ─── Posts (200) ──────────────────────────────────────────────────────────
  const postContents = [
    "Just finished a 10km run — feeling unstoppable!",
    "Can we talk about how good this coffee is? Absolutely perfect morning.",
    "Working on a new project and the progress is looking amazing!",
    "Sunsets like this make everything worth it.",
    "Finally read that book everyone's been talking about. 10/10 recommend.",
    "Hot take: tabs are better than spaces. Fight me.",
    "Just cooked a new recipe and it turned out better than expected!",
    "Reminder: it's okay to take breaks and recharge.",
    "The city looks different at 2am. There's something magical about it.",
    "Three things I'm grateful for today: good food, good friends, good music.",
    "Started learning guitar last month — my fingers hurt but I love it.",
    "Nothing beats a lazy Sunday morning with nowhere to be.",
    "Productivity tip: turn off notifications for 2 hours a day. Life-changing.",
    "Just watched the most mind-bending documentary. Still processing it.",
    "Some days you just need to vent to the internet, you know?",
    "My plant grew a new leaf and I've never been more proud of anything.",
    "Road trip planned for next month. Any recommendations for stops?",
    "There's something therapeutic about organizing your entire desk.",
    "Tried a new café today — the vibes were immaculate.",
    "Completed my first open source contribution! Feels surreal.",
    "Overthinking is just creativity without direction.",
    "Finished a side project I've been putting off for months. Relief.",
    "The best investment you can make is in yourself.",
    "Morning routine update: added meditation and it's been a game changer.",
    "Lost track of time coding and suddenly it's midnight.",
    "New haircut! Sometimes small changes make a big difference.",
    "Been journaling for 30 days straight. Highly recommend it.",
    "Sometimes the most productive thing you can do is walk away.",
    "Watched the sunrise today. First time in a long time.",
    "Good news: the bug I've been chasing for days is finally fixed.",
    "Reading more physical books this year — no more doom scrolling.",
    "I think I finally understand recursion.",
    "Cooked for the whole family today. The kitchen smells amazing.",
    "Started a 30-day drawing challenge. Day 1 complete!",
    "The best conversations happen at midnight for some reason.",
    "Cleaned out my wardrobe. Feeling so much lighter.",
    "Took a digital detox this weekend. Would recommend.",
    "Just discovered a new band and I haven't listened to anything else.",
    "Made homemade bread for the first time. It actually worked!",
    "Grateful for the small things today — warm coffee, good light, quiet morning.",
    "Shipped something today that I'm genuinely proud of.",
    "The best way to predict the future is to build it.",
    "Sometimes you just need to start — perfection is the enemy of done.",
    "Weekend plans: absolutely nothing and I am thriving.",
    "Learning to say no is one of the best things I've ever done.",
    "Finally organized my photo library. Three years of memories.",
    "Hot take: sleep is the most underrated productivity hack.",
    "Wrote 1000 words today. Small wins count.",
    "Went for a walk without headphones. Heard actual birds. Recommend.",
    "Debugging at 11pm hits different. Not in a good way.",
  ];

  function daysAgo(n) {
    return new Date(Date.now() - n * 86400000);
  }

  const posts = [];
  const postDefs = [
    { content: postContents[0],  authorIndex: 0,  createdAt: daysAgo(365) },
    { content: postContents[1],  authorIndex: 1,  createdAt: daysAgo(360) },
    { content: postContents[2],  authorIndex: 2,  createdAt: daysAgo(355) },
    { content: postContents[3],  authorIndex: 3,  createdAt: daysAgo(350) },
    { content: postContents[4],  authorIndex: 4,  createdAt: daysAgo(345) },
    { content: postContents[5],  authorIndex: 5,  createdAt: daysAgo(340) },
    { content: postContents[6],  authorIndex: 6,  createdAt: daysAgo(335) },
    { content: postContents[7],  authorIndex: 7,  createdAt: daysAgo(330) },
    { content: postContents[8],  authorIndex: 8,  createdAt: daysAgo(325) },
    { content: postContents[9],  authorIndex: 9,  createdAt: daysAgo(320) },
    { content: postContents[10], authorIndex: 10, createdAt: daysAgo(315) },
    { content: postContents[11], authorIndex: 11, createdAt: daysAgo(310) },
    { content: postContents[12], authorIndex: 12, createdAt: daysAgo(305) },
    { content: postContents[13], authorIndex: 13, createdAt: daysAgo(300) },
    { content: postContents[14], authorIndex: 14, createdAt: daysAgo(295) },
    { content: postContents[15], authorIndex: 15, createdAt: daysAgo(290) },
    { content: postContents[16], authorIndex: 16, createdAt: daysAgo(285) },
    { content: postContents[17], authorIndex: 17, createdAt: daysAgo(280) },
    { content: postContents[18], authorIndex: 18, createdAt: daysAgo(275) },
    { content: postContents[19], authorIndex: 19, createdAt: daysAgo(270) },
    { content: postContents[20], authorIndex: 20, createdAt: daysAgo(265) },
    { content: postContents[21], authorIndex: 21, createdAt: daysAgo(260) },
    { content: postContents[22], authorIndex: 22, createdAt: daysAgo(255) },
    { content: postContents[23], authorIndex: 23, createdAt: daysAgo(250) },
    { content: postContents[24], authorIndex: 24, createdAt: daysAgo(245) },
    { content: postContents[25], authorIndex: 25, createdAt: daysAgo(240) },
    { content: postContents[26], authorIndex: 26, createdAt: daysAgo(235) },
    { content: postContents[27], authorIndex: 27, createdAt: daysAgo(230) },
    { content: postContents[28], authorIndex: 28, createdAt: daysAgo(225) },
    { content: postContents[29], authorIndex: 29, createdAt: daysAgo(220) },
    { content: postContents[30], authorIndex: 30, createdAt: daysAgo(215) },
    { content: postContents[31], authorIndex: 31, createdAt: daysAgo(210) },
    { content: postContents[32], authorIndex: 32, createdAt: daysAgo(205) },
    { content: postContents[33], authorIndex: 33, createdAt: daysAgo(200) },
    { content: postContents[34], authorIndex: 34, createdAt: daysAgo(195) },
    { content: postContents[35], authorIndex: 35, createdAt: daysAgo(190) },
    { content: postContents[36], authorIndex: 36, createdAt: daysAgo(185) },
    { content: postContents[37], authorIndex: 37, createdAt: daysAgo(180) },
    { content: postContents[38], authorIndex: 38, createdAt: daysAgo(175) },
    { content: postContents[39], authorIndex: 39, createdAt: daysAgo(170) },
    { content: postContents[40], authorIndex: 40, createdAt: daysAgo(165) },
    { content: postContents[41], authorIndex: 41, createdAt: daysAgo(160) },
    { content: postContents[42], authorIndex: 42, createdAt: daysAgo(155) },
    { content: postContents[43], authorIndex: 43, createdAt: daysAgo(150) },
    { content: postContents[44], authorIndex: 44, createdAt: daysAgo(145) },
    { content: postContents[45], authorIndex: 45, createdAt: daysAgo(140) },
    { content: postContents[46], authorIndex: 46, createdAt: daysAgo(135) },
    { content: postContents[47], authorIndex: 47, createdAt: daysAgo(130) },
    { content: postContents[48], authorIndex: 48, createdAt: daysAgo(125) },
    { content: postContents[49], authorIndex: 49, createdAt: daysAgo(120) },
    // second round — same pool recycled with different authors and dates
    { content: postContents[0],  authorIndex: 50, createdAt: daysAgo(119) },
    { content: postContents[1],  authorIndex: 51, createdAt: daysAgo(118) },
    { content: postContents[2],  authorIndex: 52, createdAt: daysAgo(117) },
    { content: postContents[3],  authorIndex: 53, createdAt: daysAgo(116) },
    { content: postContents[4],  authorIndex: 54, createdAt: daysAgo(115) },
    { content: postContents[5],  authorIndex: 55, createdAt: daysAgo(114) },
    { content: postContents[6],  authorIndex: 56, createdAt: daysAgo(113) },
    { content: postContents[7],  authorIndex: 57, createdAt: daysAgo(112) },
    { content: postContents[8],  authorIndex: 58, createdAt: daysAgo(111) },
    { content: postContents[9],  authorIndex: 59, createdAt: daysAgo(110) },
    { content: postContents[10], authorIndex: 60, createdAt: daysAgo(109) },
    { content: postContents[11], authorIndex: 61, createdAt: daysAgo(108) },
    { content: postContents[12], authorIndex: 62, createdAt: daysAgo(107) },
    { content: postContents[13], authorIndex: 63, createdAt: daysAgo(106) },
    { content: postContents[14], authorIndex: 64, createdAt: daysAgo(105) },
    { content: postContents[15], authorIndex: 65, createdAt: daysAgo(104) },
    { content: postContents[16], authorIndex: 66, createdAt: daysAgo(103) },
    { content: postContents[17], authorIndex: 67, createdAt: daysAgo(102) },
    { content: postContents[18], authorIndex: 68, createdAt: daysAgo(101) },
    { content: postContents[19], authorIndex: 69, createdAt: daysAgo(100) },
    { content: postContents[20], authorIndex: 70, createdAt: daysAgo(99) },
    { content: postContents[21], authorIndex: 71, createdAt: daysAgo(98) },
    { content: postContents[22], authorIndex: 72, createdAt: daysAgo(97) },
    { content: postContents[23], authorIndex: 73, createdAt: daysAgo(96) },
    { content: postContents[24], authorIndex: 74, createdAt: daysAgo(95) },
    { content: postContents[25], authorIndex: 75, createdAt: daysAgo(94) },
    { content: postContents[26], authorIndex: 76, createdAt: daysAgo(93) },
    { content: postContents[27], authorIndex: 77, createdAt: daysAgo(92) },
    { content: postContents[28], authorIndex: 78, createdAt: daysAgo(91) },
    { content: postContents[29], authorIndex: 79, createdAt: daysAgo(90) },
    { content: postContents[30], authorIndex: 80, createdAt: daysAgo(89) },
    { content: postContents[31], authorIndex: 81, createdAt: daysAgo(88) },
    { content: postContents[32], authorIndex: 82, createdAt: daysAgo(87) },
    { content: postContents[33], authorIndex: 83, createdAt: daysAgo(86) },
    { content: postContents[34], authorIndex: 84, createdAt: daysAgo(85) },
    { content: postContents[35], authorIndex: 85, createdAt: daysAgo(84) },
    { content: postContents[36], authorIndex: 86, createdAt: daysAgo(83) },
    { content: postContents[37], authorIndex: 87, createdAt: daysAgo(82) },
    { content: postContents[38], authorIndex: 88, createdAt: daysAgo(81) },
    { content: postContents[39], authorIndex: 89, createdAt: daysAgo(80) },
    { content: postContents[40], authorIndex: 90, createdAt: daysAgo(79) },
    { content: postContents[41], authorIndex: 91, createdAt: daysAgo(78) },
    { content: postContents[42], authorIndex: 92, createdAt: daysAgo(77) },
    { content: postContents[43], authorIndex: 93, createdAt: daysAgo(76) },
    { content: postContents[44], authorIndex: 94, createdAt: daysAgo(75) },
    { content: postContents[45], authorIndex: 95, createdAt: daysAgo(74) },
    { content: postContents[46], authorIndex: 96, createdAt: daysAgo(73) },
    { content: postContents[47], authorIndex: 97, createdAt: daysAgo(72) },
    { content: postContents[48], authorIndex: 98, createdAt: daysAgo(71) },
    { content: postContents[49], authorIndex: 99, createdAt: daysAgo(70) },
    // third batch – authors cycling back
    { content: "Just hit 1000 followers — thank you all so much!",        authorIndex: 0,  createdAt: daysAgo(69) },
    { content: "Late-night coding session. The focus is unreal right now.", authorIndex: 5,  createdAt: daysAgo(68) },
    { content: "Meal-prepped for the whole week. Future me says thanks.",   authorIndex: 10, createdAt: daysAgo(67) },
    { content: "Watched an old film tonight. Pure cinema.",                 authorIndex: 15, createdAt: daysAgo(66) },
    { content: "Finally got a standing desk. My back is rejoicing.",        authorIndex: 20, createdAt: daysAgo(65) },
    { content: "Morning run done. Endorphins are real.",                    authorIndex: 25, createdAt: daysAgo(64) },
    { content: "Just pushed a major refactor. Code is so clean now.",       authorIndex: 30, createdAt: daysAgo(63) },
    { content: "Tried intermittent fasting for a week. Interesting.",       authorIndex: 35, createdAt: daysAgo(62) },
    { content: "The sky tonight was absolutely breathtaking.",              authorIndex: 40, createdAt: daysAgo(61) },
    { content: "Got promoted today. Hard work pays off.",                   authorIndex: 45, createdAt: daysAgo(60) },
    { content: "Started a new online course. Three chapters in already.",   authorIndex: 50, createdAt: daysAgo(59) },
    { content: "Bought a new mechanical keyboard. My fingers are happy.",   authorIndex: 55, createdAt: daysAgo(58) },
    { content: "Cleaned the apartment — feels like a brand new space.",     authorIndex: 60, createdAt: daysAgo(57) },
    { content: "First time trying cold brew. I'm a convert now.",           authorIndex: 65, createdAt: daysAgo(56) },
    { content: "Journaling every morning has changed my mindset.",          authorIndex: 70, createdAt: daysAgo(55) },
    { content: "Finally finished that 1000-piece puzzle. Two weeks later.", authorIndex: 75, createdAt: daysAgo(54) },
    { content: "Planted a herb garden on the balcony. Smells amazing.",     authorIndex: 80, createdAt: daysAgo(53) },
    { content: "Learned a new CSS trick today. CSS never stops surprising.",authorIndex: 85, createdAt: daysAgo(52) },
    { content: "Stayed off social media all day. Actually productive.",     authorIndex: 90, createdAt: daysAgo(51) },
    { content: "Surprised a friend with their favorite food. Best feeling.",authorIndex: 95, createdAt: daysAgo(50) },
    { content: "Revisited an old project. How much I've grown!",            authorIndex: 1,  createdAt: daysAgo(49) },
    { content: "Today's win: fixed a bug that had me stuck for 3 days.",    authorIndex: 6,  createdAt: daysAgo(48) },
    { content: "A good walk clears my head better than anything.",          authorIndex: 11, createdAt: daysAgo(47) },
    { content: "Baked cookies from scratch. The house smells wonderful.",   authorIndex: 16, createdAt: daysAgo(46) },
    { content: "Joined a local running club. Community > solo runs.",       authorIndex: 21, createdAt: daysAgo(45) },
    { content: "Deep cleaned my laptop and it runs like new.",              authorIndex: 26, createdAt: daysAgo(44) },
    { content: "First open mic night. Terrifying and worth it.",            authorIndex: 31, createdAt: daysAgo(43) },
    { content: "Read 50 pages before bed. Best nighttime habit.",           authorIndex: 36, createdAt: daysAgo(42) },
    { content: "Tried a new hiking trail. The view at the top was worth it.",authorIndex: 41, createdAt: daysAgo(41) },
    { content: "Gave a presentation today and nailed it.",                  authorIndex: 46, createdAt: daysAgo(40) },
    { content: "New playlist incoming — been curating for weeks.",          authorIndex: 51, createdAt: daysAgo(39) },
    { content: "Learned to say 'I don't know' without shame.",              authorIndex: 56, createdAt: daysAgo(38) },
    { content: "Deleted 2000 unread emails. Digital hygiene matters.",      authorIndex: 61, createdAt: daysAgo(37) },
    { content: "Tried a pottery class. Turns out I'm terrible. Loved it.",  authorIndex: 66, createdAt: daysAgo(36) },
    { content: "Grateful for a slow, quiet day with nothing urgent.",       authorIndex: 71, createdAt: daysAgo(35) },
    { content: "Wrote a function in 3 lines that used to take 30.",         authorIndex: 76, createdAt: daysAgo(34) },
    { content: "Cooked the recipe wrong but it somehow tasted better.",     authorIndex: 81, createdAt: daysAgo(33) },
    { content: "Long video call with a friend I hadn't spoken to in months.",authorIndex: 86, createdAt: daysAgo(32) },
    { content: "Watched a TED talk that completely shifted my perspective.", authorIndex: 91, createdAt: daysAgo(31) },
    { content: "Friday night in with a good book. Perfect.",                authorIndex: 96, createdAt: daysAgo(30) },
    { content: "My side project just got its first star on GitHub!",        authorIndex: 2,  createdAt: daysAgo(29) },
    { content: "Trying to drink more water. Day 3 of this challenge.",      authorIndex: 7,  createdAt: daysAgo(28) },
    { content: "The feedback I got today was hard but fair. Growing.",      authorIndex: 12, createdAt: daysAgo(27) },
    { content: "Wore the outfit I was 'saving for a special occasion.'",    authorIndex: 17, createdAt: daysAgo(26) },
    { content: "Nothing motivates me more than seeing progress.",           authorIndex: 22, createdAt: daysAgo(25) },
    { content: "Spent the evening with no screens. Surprisingly great.",    authorIndex: 27, createdAt: daysAgo(24) },
    { content: "Adopted a new morning routine. Already feels transformative.",authorIndex: 32, createdAt: daysAgo(23) },
    { content: "Connected with a mentor today. Invaluable conversation.",   authorIndex: 37, createdAt: daysAgo(22) },
    { content: "Hit a personal record at the gym. Feeling great!",          authorIndex: 42, createdAt: daysAgo(21) },
    { content: "Preordered a book I've been waiting a year for.",           authorIndex: 47, createdAt: daysAgo(20) },
    { content: "Finished my first marathon. I can barely walk. Worth it.",  authorIndex: 52, createdAt: daysAgo(19) },
    { content: "Had the best conversation with a stranger on the train.",   authorIndex: 57, createdAt: daysAgo(18) },
    { content: "Learned that slowing down is not the same as giving up.",   authorIndex: 62, createdAt: daysAgo(17) },
    { content: "Finally fixed the memory leak. Ship it!",                   authorIndex: 67, createdAt: daysAgo(16) },
    { content: "Tried journaling in the evening instead of morning. Better.",authorIndex: 72, createdAt: daysAgo(15) },
    { content: "New office setup is complete. Productivity unlocked.",       authorIndex: 77, createdAt: daysAgo(14) },
    { content: "Started writing a newsletter. First edition is out!",       authorIndex: 82, createdAt: daysAgo(13) },
    { content: "Went to a farmers market for the first time. Loved it.",    authorIndex: 87, createdAt: daysAgo(12) },
    { content: "Three months sober. Feeling the best I've felt in years.",  authorIndex: 92, createdAt: daysAgo(11) },
    { content: "Good design is invisible. I finally understand this.",      authorIndex: 97, createdAt: daysAgo(10) },
    { content: "Built a small CLI tool that saves me an hour every week.",  authorIndex: 3,  createdAt: daysAgo(9) },
    { content: "Taught my little sibling to code today. So proud.",         authorIndex: 8,  createdAt: daysAgo(8) },
    { content: "The team shipped the feature. We crushed it.",              authorIndex: 13, createdAt: daysAgo(7) },
    { content: "Closed my laptop at 6pm for once. Big deal for me.",        authorIndex: 18, createdAt: daysAgo(6) },
    { content: "Had a great review — manager said keep doing what I'm doing.",authorIndex: 23, createdAt: daysAgo(5) },
    { content: "Spent Sunday reading in the park. 10/10 would recommend.",  authorIndex: 28, createdAt: daysAgo(4) },
    { content: "A year ago I couldn't do this. Look at me now.",            authorIndex: 33, createdAt: daysAgo(3) },
    { content: "New week, same goals, better energy.",                      authorIndex: 38, createdAt: daysAgo(2) },
    { content: "Grateful for every small step forward.",                    authorIndex: 43, createdAt: daysAgo(1) },
    { content: "Orbit is live! So excited to share what I've been building.",authorIndex: 48, createdAt: daysAgo(0) },
    // fourth batch — 30 more to reach 200
    { content: "The problem wasn't the code. It was my assumptions.",        authorIndex: 4,  createdAt: daysAgo(69) },
    { content: "Consistency beats motivation every single time.",             authorIndex: 9,  createdAt: daysAgo(68) },
    { content: "Shipped v2 today. Users are loving the new features.",        authorIndex: 14, createdAt: daysAgo(67) },
    { content: "Sometimes the answer is just to sleep on it.",               authorIndex: 19, createdAt: daysAgo(66) },
    { content: "Joined a new team today. Exciting and terrifying.",           authorIndex: 24, createdAt: daysAgo(65) },
    { content: "Built something in a weekend that I've been planning for a year.", authorIndex: 29, createdAt: daysAgo(64) },
    { content: "The best part of remote work is the commute.",               authorIndex: 34, createdAt: daysAgo(63) },
    { content: "Five years in tech and I still google the basics daily.",     authorIndex: 39, createdAt: daysAgo(62) },
    { content: "Meditation for 10 minutes > scrolling for 60.",              authorIndex: 44, createdAt: daysAgo(61) },
    { content: "Gave honest feedback today. Hard but necessary.",             authorIndex: 49, createdAt: daysAgo(60) },
    { content: "The documentation I wish had existed when I started.",        authorIndex: 54, createdAt: daysAgo(59) },
    { content: "New personal record: 5 PRs merged in one day.",              authorIndex: 59, createdAt: daysAgo(58) },
    { content: "Spent an hour just thinking. No devices. Highly recommend.", authorIndex: 64, createdAt: daysAgo(57) },
    { content: "My pair-programming partner is my rubber duck.",             authorIndex: 69, createdAt: daysAgo(56) },
    { content: "Life update: I finally got my first apartment!",             authorIndex: 74, createdAt: daysAgo(55) },
    { content: "Learned more from this failure than any success.",           authorIndex: 79, createdAt: daysAgo(54) },
    { content: "Finished writing the API docs. The most underrated work.",   authorIndex: 84, createdAt: daysAgo(53) },
    { content: "The code review comments that changed how I think.",         authorIndex: 89, createdAt: daysAgo(52) },
    { content: "Took a solo trip this weekend. The reset I needed.",         authorIndex: 94, createdAt: daysAgo(51) },
    { content: "Hot take: the README is more important than the code.",       authorIndex: 99, createdAt: daysAgo(50) },
    { content: "It's okay to not have all the answers. That's what the team is for.", authorIndex: 3, createdAt: daysAgo(49) },
    { content: "Three cups of coffee in. Send help. Or more coffee.",        authorIndex: 8,  createdAt: daysAgo(48) },
    { content: "Finally switched to dark mode everywhere. My eyes thank me.",authorIndex: 13, createdAt: daysAgo(47) },
    { content: "Presented at a local meetup. The community was amazing.",    authorIndex: 18, createdAt: daysAgo(46) },
    { content: "Deleted 500 lines of code and the feature still works.",     authorIndex: 23, createdAt: daysAgo(45) },
    { content: "Sunday recharge mode: no notifications, all vibes.",         authorIndex: 28, createdAt: daysAgo(44) },
    { content: "Wrote tests first for the first time. Game changer.",        authorIndex: 33, createdAt: daysAgo(43) },
    { content: "The internet is vast. There's always someone who wrote about your bug.", authorIndex: 38, createdAt: daysAgo(42) },
    { content: "Landed my dream internship today. So grateful.",             authorIndex: 43, createdAt: daysAgo(41) },
    { content: "End of month reflection: more wins than losses. I'll take it.", authorIndex: 48, createdAt: daysAgo(40) },
  ];

  for (const def of postDefs) {
    const post = await prisma.post.create({
      data: {
        content:   def.content,
        createdAt: def.createdAt,
        updatedAt: def.createdAt,
        authorId:  users[def.authorIndex].id,
      },
    });
    posts.push(post);
  }
  console.log(`Created ${posts.length} posts.`);

  // ─── Comments ─────────────────────────────────────────────────────────────
  const commentDefs = [
    { content: "This is so relatable!",                    authorIndex: 1,  postIndex: 0  },
    { content: "Love this so much!",                       authorIndex: 2,  postIndex: 0  },
    { content: "Keep it up!",                              authorIndex: 3,  postIndex: 1  },
    { content: "This made my day.",                        authorIndex: 4,  postIndex: 1  },
    { content: "Agreed 100%!",                             authorIndex: 5,  postIndex: 2  },
    { content: "I needed to hear this today.",             authorIndex: 6,  postIndex: 2  },
    { content: "Same exact feeling!",                      authorIndex: 7,  postIndex: 3  },
    { content: "You're an inspiration!",                   authorIndex: 8,  postIndex: 3  },
    { content: "This is underrated content.",              authorIndex: 9,  postIndex: 4  },
    { content: "Couldn't agree more.",                     authorIndex: 10, postIndex: 4  },
    { content: "Wow, didn't think of it that way.",        authorIndex: 11, postIndex: 5  },
    { content: "Great perspective!",                       authorIndex: 12, postIndex: 5  },
    { content: "This is goals.",                           authorIndex: 13, postIndex: 6  },
    { content: "More of this please!",                     authorIndex: 14, postIndex: 6  },
    { content: "This is the content I'm here for.",        authorIndex: 15, postIndex: 7  },
    { content: "Sending good vibes your way!",             authorIndex: 16, postIndex: 7  },
    { content: "You always post the best stuff.",          authorIndex: 17, postIndex: 8  },
    { content: "Okay but this is exactly me.",             authorIndex: 18, postIndex: 8  },
    { content: "Saved this for later.",                    authorIndex: 19, postIndex: 9  },
    { content: "Real talk!",                               authorIndex: 20, postIndex: 9  },
    { content: "This hit differently today.",              authorIndex: 21, postIndex: 10 },
    { content: "Appreciate you sharing this.",             authorIndex: 22, postIndex: 10 },
    { content: "We're all in this together!",              authorIndex: 23, postIndex: 11 },
    { content: "Facts only.",                              authorIndex: 24, postIndex: 11 },
    { content: "This deserves way more likes.",            authorIndex: 25, postIndex: 12 },
    { content: "Absolutely love this post.",               authorIndex: 26, postIndex: 12 },
    { content: "This is pure gold.",                       authorIndex: 27, postIndex: 13 },
    { content: "You just described my life perfectly.",    authorIndex: 28, postIndex: 13 },
    { content: "Sharing this with everyone I know.",       authorIndex: 29, postIndex: 14 },
    { content: "This is so true and I feel seen.",         authorIndex: 30, postIndex: 14 },
    { content: "Thank you for posting this!",              authorIndex: 31, postIndex: 15 },
    { content: "Best post I've seen all week.",            authorIndex: 32, postIndex: 15 },
    { content: "Exactly what I needed today.",             authorIndex: 33, postIndex: 16 },
    { content: "Never thought about it like that before.", authorIndex: 34, postIndex: 16 },
    { content: "This gives me so much motivation.",        authorIndex: 35, postIndex: 17 },
    { content: "You're doing amazing, seriously.",         authorIndex: 36, postIndex: 17 },
    { content: "I feel this in my soul.",                  authorIndex: 37, postIndex: 18 },
    { content: "Bookmarked. Coming back to this later.",   authorIndex: 38, postIndex: 18 },
    { content: "This community is everything.",            authorIndex: 39, postIndex: 19 },
    { content: "Words to live by honestly.",               authorIndex: 40, postIndex: 19 },
    { content: "I aspire to have your energy.",            authorIndex: 41, postIndex: 20 },
    { content: "Can relate to this on a spiritual level.", authorIndex: 42, postIndex: 20 },
    { content: "Thanks for the reminder!",                 authorIndex: 43, postIndex: 21 },
    { content: "This is why I love this platform.",        authorIndex: 44, postIndex: 21 },
    { content: "Short but so impactful.",                  authorIndex: 45, postIndex: 22 },
    { content: "One of the best things I've read today.",  authorIndex: 46, postIndex: 22 },
    { content: "Dropping gems as always!",                 authorIndex: 47, postIndex: 23 },
    { content: "My screen time is all this app now.",      authorIndex: 48, postIndex: 23 },
    { content: "How is this not more popular?",            authorIndex: 49, postIndex: 24 },
    { content: "Screenshotting this for my vision board.", authorIndex: 50, postIndex: 24 },
    { content: "This is the push I needed.",               authorIndex: 51, postIndex: 25 },
    { content: "Wholesome content, love it.",              authorIndex: 52, postIndex: 25 },
    { content: "You literally read my mind.",              authorIndex: 53, postIndex: 26 },
    { content: "Commenting so I can find this later.",     authorIndex: 54, postIndex: 26 },
    { content: "Absolutely relatable.",                    authorIndex: 55, postIndex: 27 },
    { content: "Keep doing what you're doing!",            authorIndex: 56, postIndex: 27 },
    { content: "A vibe and a half.",                       authorIndex: 57, postIndex: 28 },
    { content: "Sending love!",                            authorIndex: 58, postIndex: 28 },
    { content: "This is why I follow you.",                authorIndex: 59, postIndex: 29 },
    { content: "Needed a good laugh, thanks!",             authorIndex: 60, postIndex: 29 },
    { content: "Facts. No notes.",                         authorIndex: 61, postIndex: 30 },
    { content: "Screaming at how accurate this is.",       authorIndex: 62, postIndex: 30 },
    { content: "You just unlocked a memory.",              authorIndex: 63, postIndex: 31 },
    { content: "Okay but why is this so deep?",            authorIndex: 64, postIndex: 31 },
    { content: "The best kind of post.",                   authorIndex: 65, postIndex: 32 },
    { content: "Straight facts.",                          authorIndex: 66, postIndex: 32 },
    { content: "I'm not crying, you're crying.",           authorIndex: 67, postIndex: 33 },
    { content: "Goals. Pure goals.",                       authorIndex: 68, postIndex: 33 },
    { content: "This is everything.",                      authorIndex: 69, postIndex: 34 },
    { content: "Can we be friends?",                       authorIndex: 70, postIndex: 34 },
    { content: "Said what needed to be said.",             authorIndex: 71, postIndex: 35 },
    { content: "This is my new motto.",                    authorIndex: 72, postIndex: 35 },
    { content: "Top tier content.",                        authorIndex: 73, postIndex: 36 },
    { content: "Every time you post it's a win.",          authorIndex: 74, postIndex: 36 },
    { content: "Adding this to my daily reminders.",       authorIndex: 75, postIndex: 37 },
    { content: "Not me tearing up a little.",              authorIndex: 76, postIndex: 37 },
    { content: "Perfectly put.",                           authorIndex: 77, postIndex: 38 },
    { content: "I live for these posts.",                  authorIndex: 78, postIndex: 38 },
    { content: "This is why the internet exists.",         authorIndex: 79, postIndex: 39 },
    { content: "Absolute fire post.",                      authorIndex: 80, postIndex: 39 },
    { content: "Wholesome and needed.",                    authorIndex: 81, postIndex: 40 },
    { content: "Never skip a post from you.",              authorIndex: 82, postIndex: 40 },
    { content: "Words of wisdom right here.",              authorIndex: 83, postIndex: 41 },
    { content: "Taking notes!",                            authorIndex: 84, postIndex: 41 },
    { content: "I feel so understood right now.",          authorIndex: 85, postIndex: 42 },
    { content: "This resonated so much.",                  authorIndex: 86, postIndex: 42 },
    { content: "Shoutout to everyone who needed this.",    authorIndex: 87, postIndex: 43 },
    { content: "My exact thoughts, perfectly worded.",     authorIndex: 88, postIndex: 43 },
    { content: "A+ content as always.",                    authorIndex: 89, postIndex: 44 },
    { content: "You never miss.",                          authorIndex: 90, postIndex: 44 },
    { content: "This brightened my whole day.",            authorIndex: 91, postIndex: 45 },
    { content: "Quality > quantity, and this is quality.", authorIndex: 92, postIndex: 45 },
    { content: "Real ones know.",                          authorIndex: 93, postIndex: 46 },
    { content: "Following for more content like this.",    authorIndex: 94, postIndex: 46 },
    { content: "The way this just described my week.",     authorIndex: 95, postIndex: 47 },
    { content: "This is art.",                             authorIndex: 96, postIndex: 47 },
    { content: "Officially my new favorite account.",      authorIndex: 97, postIndex: 48 },
    { content: "Long may you post.",                       authorIndex: 98, postIndex: 48 },
    { content: "This is the moment.",                      authorIndex: 99, postIndex: 49 },
    { content: "I needed to see this today, truly.",       authorIndex: 0,  postIndex: 49 },
  ];

  for (const def of commentDefs) {
    await prisma.comment.create({
      data: {
        content:   def.content,
        createdAt: new Date(Date.now() - Math.floor(Math.random() * 86400000 * 300)),
        authorId:  users[def.authorIndex].id,
        postId:    posts[def.postIndex].id,
      },
    });
  }
  console.log(`Created ${commentDefs.length} comments.`);

  // ─── Likes ────────────────────────────────────────────────────────────────
  const likeDefs = [
    { userIndex: 1,  postIndex: 0  }, { userIndex: 2,  postIndex: 0  }, { userIndex: 3,  postIndex: 0  },
    { userIndex: 4,  postIndex: 1  }, { userIndex: 5,  postIndex: 1  }, { userIndex: 6,  postIndex: 1  },
    { userIndex: 7,  postIndex: 2  }, { userIndex: 8,  postIndex: 2  }, { userIndex: 9,  postIndex: 2  },
    { userIndex: 10, postIndex: 3  }, { userIndex: 11, postIndex: 3  }, { userIndex: 12, postIndex: 3  },
    { userIndex: 13, postIndex: 4  }, { userIndex: 14, postIndex: 4  }, { userIndex: 15, postIndex: 4  },
    { userIndex: 16, postIndex: 5  }, { userIndex: 17, postIndex: 5  }, { userIndex: 18, postIndex: 5  },
    { userIndex: 19, postIndex: 6  }, { userIndex: 20, postIndex: 6  }, { userIndex: 21, postIndex: 6  },
    { userIndex: 22, postIndex: 7  }, { userIndex: 23, postIndex: 7  }, { userIndex: 24, postIndex: 7  },
    { userIndex: 25, postIndex: 8  }, { userIndex: 26, postIndex: 8  }, { userIndex: 27, postIndex: 8  },
    { userIndex: 28, postIndex: 9  }, { userIndex: 29, postIndex: 9  }, { userIndex: 30, postIndex: 9  },
    { userIndex: 31, postIndex: 10 }, { userIndex: 32, postIndex: 10 }, { userIndex: 33, postIndex: 10 },
    { userIndex: 34, postIndex: 11 }, { userIndex: 35, postIndex: 11 }, { userIndex: 36, postIndex: 11 },
    { userIndex: 37, postIndex: 12 }, { userIndex: 38, postIndex: 12 }, { userIndex: 39, postIndex: 12 },
    { userIndex: 40, postIndex: 13 }, { userIndex: 41, postIndex: 13 }, { userIndex: 42, postIndex: 13 },
    { userIndex: 43, postIndex: 14 }, { userIndex: 44, postIndex: 14 }, { userIndex: 45, postIndex: 14 },
    { userIndex: 46, postIndex: 15 }, { userIndex: 47, postIndex: 15 }, { userIndex: 48, postIndex: 15 },
    { userIndex: 49, postIndex: 16 }, { userIndex: 50, postIndex: 16 }, { userIndex: 51, postIndex: 16 },
    { userIndex: 52, postIndex: 17 }, { userIndex: 53, postIndex: 17 }, { userIndex: 54, postIndex: 17 },
    { userIndex: 55, postIndex: 18 }, { userIndex: 56, postIndex: 18 }, { userIndex: 57, postIndex: 18 },
    { userIndex: 58, postIndex: 19 }, { userIndex: 59, postIndex: 19 }, { userIndex: 60, postIndex: 19 },
    { userIndex: 61, postIndex: 20 }, { userIndex: 62, postIndex: 20 }, { userIndex: 63, postIndex: 20 },
    { userIndex: 64, postIndex: 21 }, { userIndex: 65, postIndex: 21 }, { userIndex: 66, postIndex: 21 },
    { userIndex: 67, postIndex: 22 }, { userIndex: 68, postIndex: 22 }, { userIndex: 69, postIndex: 22 },
    { userIndex: 70, postIndex: 23 }, { userIndex: 71, postIndex: 23 }, { userIndex: 72, postIndex: 23 },
    { userIndex: 73, postIndex: 24 }, { userIndex: 74, postIndex: 24 }, { userIndex: 75, postIndex: 24 },
    { userIndex: 76, postIndex: 25 }, { userIndex: 77, postIndex: 25 }, { userIndex: 78, postIndex: 25 },
    { userIndex: 79, postIndex: 26 }, { userIndex: 80, postIndex: 26 }, { userIndex: 81, postIndex: 26 },
    { userIndex: 82, postIndex: 27 }, { userIndex: 83, postIndex: 27 }, { userIndex: 84, postIndex: 27 },
    { userIndex: 85, postIndex: 28 }, { userIndex: 86, postIndex: 28 }, { userIndex: 87, postIndex: 28 },
    { userIndex: 88, postIndex: 29 }, { userIndex: 89, postIndex: 29 }, { userIndex: 90, postIndex: 29 },
    { userIndex: 91, postIndex: 30 }, { userIndex: 92, postIndex: 30 }, { userIndex: 93, postIndex: 30 },
    { userIndex: 94, postIndex: 31 }, { userIndex: 95, postIndex: 31 }, { userIndex: 96, postIndex: 31 },
    { userIndex: 97, postIndex: 32 }, { userIndex: 98, postIndex: 32 }, { userIndex: 99, postIndex: 32 },
    { userIndex: 0,  postIndex: 33 }, { userIndex: 1,  postIndex: 33 }, { userIndex: 2,  postIndex: 33 },
    { userIndex: 3,  postIndex: 34 }, { userIndex: 4,  postIndex: 34 }, { userIndex: 5,  postIndex: 34 },
    { userIndex: 6,  postIndex: 35 }, { userIndex: 7,  postIndex: 35 }, { userIndex: 8,  postIndex: 35 },
    { userIndex: 9,  postIndex: 36 }, { userIndex: 10, postIndex: 36 }, { userIndex: 11, postIndex: 36 },
    { userIndex: 12, postIndex: 37 }, { userIndex: 13, postIndex: 37 }, { userIndex: 14, postIndex: 37 },
    { userIndex: 15, postIndex: 38 }, { userIndex: 16, postIndex: 38 }, { userIndex: 17, postIndex: 38 },
    { userIndex: 18, postIndex: 39 }, { userIndex: 19, postIndex: 39 }, { userIndex: 20, postIndex: 39 },
    { userIndex: 21, postIndex: 40 }, { userIndex: 22, postIndex: 40 }, { userIndex: 23, postIndex: 40 },
    { userIndex: 24, postIndex: 41 }, { userIndex: 25, postIndex: 41 }, { userIndex: 26, postIndex: 41 },
    { userIndex: 27, postIndex: 42 }, { userIndex: 28, postIndex: 42 }, { userIndex: 29, postIndex: 42 },
    { userIndex: 30, postIndex: 43 }, { userIndex: 31, postIndex: 43 }, { userIndex: 32, postIndex: 43 },
    { userIndex: 33, postIndex: 44 }, { userIndex: 34, postIndex: 44 }, { userIndex: 35, postIndex: 44 },
    { userIndex: 36, postIndex: 45 }, { userIndex: 37, postIndex: 45 }, { userIndex: 38, postIndex: 45 },
    { userIndex: 39, postIndex: 46 }, { userIndex: 40, postIndex: 46 }, { userIndex: 41, postIndex: 46 },
    { userIndex: 42, postIndex: 47 }, { userIndex: 43, postIndex: 47 }, { userIndex: 44, postIndex: 47 },
    { userIndex: 45, postIndex: 48 }, { userIndex: 46, postIndex: 48 }, { userIndex: 47, postIndex: 48 },
    { userIndex: 48, postIndex: 49 }, { userIndex: 49, postIndex: 49 }, { userIndex: 50, postIndex: 49 },
    { userIndex: 51, postIndex: 50 }, { userIndex: 52, postIndex: 51 }, { userIndex: 53, postIndex: 52 },
    { userIndex: 54, postIndex: 53 }, { userIndex: 55, postIndex: 54 }, { userIndex: 56, postIndex: 55 },
    { userIndex: 57, postIndex: 56 }, { userIndex: 58, postIndex: 57 }, { userIndex: 59, postIndex: 58 },
    { userIndex: 60, postIndex: 59 }, { userIndex: 61, postIndex: 60 }, { userIndex: 62, postIndex: 61 },
    { userIndex: 63, postIndex: 62 }, { userIndex: 64, postIndex: 63 }, { userIndex: 65, postIndex: 64 },
    { userIndex: 66, postIndex: 65 }, { userIndex: 67, postIndex: 66 }, { userIndex: 68, postIndex: 67 },
    { userIndex: 69, postIndex: 68 }, { userIndex: 70, postIndex: 69 }, { userIndex: 71, postIndex: 70 },
    { userIndex: 72, postIndex: 71 }, { userIndex: 73, postIndex: 72 }, { userIndex: 74, postIndex: 73 },
    { userIndex: 75, postIndex: 74 }, { userIndex: 76, postIndex: 75 }, { userIndex: 77, postIndex: 76 },
    { userIndex: 78, postIndex: 77 }, { userIndex: 79, postIndex: 78 }, { userIndex: 80, postIndex: 79 },
    { userIndex: 81, postIndex: 80 }, { userIndex: 82, postIndex: 81 }, { userIndex: 83, postIndex: 82 },
    { userIndex: 84, postIndex: 83 }, { userIndex: 85, postIndex: 84 }, { userIndex: 86, postIndex: 85 },
    { userIndex: 87, postIndex: 86 }, { userIndex: 88, postIndex: 87 }, { userIndex: 89, postIndex: 88 },
    { userIndex: 90, postIndex: 89 }, { userIndex: 91, postIndex: 90 }, { userIndex: 92, postIndex: 91 },
    { userIndex: 93, postIndex: 92 }, { userIndex: 94, postIndex: 93 }, { userIndex: 95, postIndex: 94 },
    { userIndex: 96, postIndex: 95 }, { userIndex: 97, postIndex: 96 }, { userIndex: 98, postIndex: 97 },
    { userIndex: 99, postIndex: 98 }, { userIndex: 0,  postIndex: 99 },
  ];

  for (const def of likeDefs) {
    await prisma.like.create({
      data: {
        createdAt: new Date(Date.now() - Math.floor(Math.random() * 86400000 * 300)),
        userId:    users[def.userIndex].id,
        postId:    posts[def.postIndex].id,
      },
    });
  }
  console.log(`Created ${likeDefs.length} likes.`);

  // ─── Follows ──────────────────────────────────────────────────────────────
  const followDefs = [
    { followerIndex: 0,  followingIndex: 1  }, { followerIndex: 0,  followingIndex: 2  },
    { followerIndex: 1,  followingIndex: 0  }, { followerIndex: 1,  followingIndex: 3  },
    { followerIndex: 2,  followingIndex: 0  }, { followerIndex: 2,  followingIndex: 4  },
    { followerIndex: 3,  followingIndex: 1  }, { followerIndex: 3,  followingIndex: 5  },
    { followerIndex: 4,  followingIndex: 2  }, { followerIndex: 4,  followingIndex: 6  },
    { followerIndex: 5,  followingIndex: 3  }, { followerIndex: 5,  followingIndex: 7  },
    { followerIndex: 6,  followingIndex: 4  }, { followerIndex: 6,  followingIndex: 8  },
    { followerIndex: 7,  followingIndex: 5  }, { followerIndex: 7,  followingIndex: 9  },
    { followerIndex: 8,  followingIndex: 6  }, { followerIndex: 8,  followingIndex: 10 },
    { followerIndex: 9,  followingIndex: 7  }, { followerIndex: 9,  followingIndex: 11 },
    { followerIndex: 10, followingIndex: 8  }, { followerIndex: 10, followingIndex: 12 },
    { followerIndex: 11, followingIndex: 9  }, { followerIndex: 11, followingIndex: 13 },
    { followerIndex: 12, followingIndex: 10 }, { followerIndex: 12, followingIndex: 14 },
    { followerIndex: 13, followingIndex: 11 }, { followerIndex: 13, followingIndex: 15 },
    { followerIndex: 14, followingIndex: 12 }, { followerIndex: 14, followingIndex: 16 },
    { followerIndex: 15, followingIndex: 13 }, { followerIndex: 15, followingIndex: 17 },
    { followerIndex: 16, followingIndex: 14 }, { followerIndex: 16, followingIndex: 18 },
    { followerIndex: 17, followingIndex: 15 }, { followerIndex: 17, followingIndex: 19 },
    { followerIndex: 18, followingIndex: 16 }, { followerIndex: 18, followingIndex: 20 },
    { followerIndex: 19, followingIndex: 17 }, { followerIndex: 19, followingIndex: 21 },
    { followerIndex: 20, followingIndex: 18 }, { followerIndex: 20, followingIndex: 22 },
    { followerIndex: 21, followingIndex: 19 }, { followerIndex: 21, followingIndex: 23 },
    { followerIndex: 22, followingIndex: 20 }, { followerIndex: 22, followingIndex: 24 },
    { followerIndex: 23, followingIndex: 21 }, { followerIndex: 23, followingIndex: 25 },
    { followerIndex: 24, followingIndex: 22 }, { followerIndex: 24, followingIndex: 26 },
    { followerIndex: 25, followingIndex: 23 }, { followerIndex: 25, followingIndex: 27 },
    { followerIndex: 26, followingIndex: 24 }, { followerIndex: 26, followingIndex: 28 },
    { followerIndex: 27, followingIndex: 25 }, { followerIndex: 27, followingIndex: 29 },
    { followerIndex: 28, followingIndex: 26 }, { followerIndex: 28, followingIndex: 30 },
    { followerIndex: 29, followingIndex: 27 }, { followerIndex: 29, followingIndex: 31 },
    { followerIndex: 30, followingIndex: 28 }, { followerIndex: 30, followingIndex: 32 },
    { followerIndex: 31, followingIndex: 29 }, { followerIndex: 31, followingIndex: 33 },
    { followerIndex: 32, followingIndex: 30 }, { followerIndex: 32, followingIndex: 34 },
    { followerIndex: 33, followingIndex: 31 }, { followerIndex: 33, followingIndex: 35 },
    { followerIndex: 34, followingIndex: 32 }, { followerIndex: 34, followingIndex: 36 },
    { followerIndex: 35, followingIndex: 33 }, { followerIndex: 35, followingIndex: 37 },
    { followerIndex: 36, followingIndex: 34 }, { followerIndex: 36, followingIndex: 38 },
    { followerIndex: 37, followingIndex: 35 }, { followerIndex: 37, followingIndex: 39 },
    { followerIndex: 38, followingIndex: 36 }, { followerIndex: 38, followingIndex: 40 },
    { followerIndex: 39, followingIndex: 37 }, { followerIndex: 39, followingIndex: 41 },
    { followerIndex: 40, followingIndex: 38 }, { followerIndex: 40, followingIndex: 42 },
    { followerIndex: 41, followingIndex: 39 }, { followerIndex: 41, followingIndex: 43 },
    { followerIndex: 42, followingIndex: 40 }, { followerIndex: 42, followingIndex: 44 },
    { followerIndex: 43, followingIndex: 41 }, { followerIndex: 43, followingIndex: 45 },
    { followerIndex: 44, followingIndex: 42 }, { followerIndex: 44, followingIndex: 46 },
    { followerIndex: 45, followingIndex: 43 }, { followerIndex: 45, followingIndex: 47 },
    { followerIndex: 46, followingIndex: 44 }, { followerIndex: 46, followingIndex: 48 },
    { followerIndex: 47, followingIndex: 45 }, { followerIndex: 47, followingIndex: 49 },
    { followerIndex: 48, followingIndex: 46 }, { followerIndex: 48, followingIndex: 50 },
    { followerIndex: 49, followingIndex: 47 }, { followerIndex: 49, followingIndex: 51 },
    { followerIndex: 50, followingIndex: 48 }, { followerIndex: 50, followingIndex: 52 },
    { followerIndex: 51, followingIndex: 49 }, { followerIndex: 51, followingIndex: 53 },
    { followerIndex: 52, followingIndex: 50 }, { followerIndex: 52, followingIndex: 54 },
    { followerIndex: 53, followingIndex: 51 }, { followerIndex: 53, followingIndex: 55 },
    { followerIndex: 54, followingIndex: 52 }, { followerIndex: 54, followingIndex: 56 },
    { followerIndex: 55, followingIndex: 53 }, { followerIndex: 55, followingIndex: 57 },
    { followerIndex: 56, followingIndex: 54 }, { followerIndex: 56, followingIndex: 58 },
    { followerIndex: 57, followingIndex: 55 }, { followerIndex: 57, followingIndex: 59 },
    { followerIndex: 58, followingIndex: 56 }, { followerIndex: 58, followingIndex: 60 },
    { followerIndex: 59, followingIndex: 57 }, { followerIndex: 59, followingIndex: 61 },
    { followerIndex: 60, followingIndex: 58 }, { followerIndex: 60, followingIndex: 62 },
    { followerIndex: 61, followingIndex: 59 }, { followerIndex: 61, followingIndex: 63 },
    { followerIndex: 62, followingIndex: 60 }, { followerIndex: 62, followingIndex: 64 },
    { followerIndex: 63, followingIndex: 61 }, { followerIndex: 63, followingIndex: 65 },
    { followerIndex: 64, followingIndex: 62 }, { followerIndex: 64, followingIndex: 66 },
    { followerIndex: 65, followingIndex: 63 }, { followerIndex: 65, followingIndex: 67 },
    { followerIndex: 66, followingIndex: 64 }, { followerIndex: 66, followingIndex: 68 },
    { followerIndex: 67, followingIndex: 65 }, { followerIndex: 67, followingIndex: 69 },
    { followerIndex: 68, followingIndex: 66 }, { followerIndex: 68, followingIndex: 70 },
    { followerIndex: 69, followingIndex: 67 }, { followerIndex: 69, followingIndex: 71 },
    { followerIndex: 70, followingIndex: 68 }, { followerIndex: 70, followingIndex: 72 },
    { followerIndex: 71, followingIndex: 69 }, { followerIndex: 71, followingIndex: 73 },
    { followerIndex: 72, followingIndex: 70 }, { followerIndex: 72, followingIndex: 74 },
    { followerIndex: 73, followingIndex: 71 }, { followerIndex: 73, followingIndex: 75 },
    { followerIndex: 74, followingIndex: 72 }, { followerIndex: 74, followingIndex: 76 },
    { followerIndex: 75, followingIndex: 73 }, { followerIndex: 75, followingIndex: 77 },
    { followerIndex: 76, followingIndex: 74 }, { followerIndex: 76, followingIndex: 78 },
    { followerIndex: 77, followingIndex: 75 }, { followerIndex: 77, followingIndex: 79 },
    { followerIndex: 78, followingIndex: 76 }, { followerIndex: 78, followingIndex: 80 },
    { followerIndex: 79, followingIndex: 77 }, { followerIndex: 79, followingIndex: 81 },
    { followerIndex: 80, followingIndex: 78 }, { followerIndex: 80, followingIndex: 82 },
    { followerIndex: 81, followingIndex: 79 }, { followerIndex: 81, followingIndex: 83 },
    { followerIndex: 82, followingIndex: 80 }, { followerIndex: 82, followingIndex: 84 },
    { followerIndex: 83, followingIndex: 81 }, { followerIndex: 83, followingIndex: 85 },
    { followerIndex: 84, followingIndex: 82 }, { followerIndex: 84, followingIndex: 86 },
    { followerIndex: 85, followingIndex: 83 }, { followerIndex: 85, followingIndex: 87 },
    { followerIndex: 86, followingIndex: 84 }, { followerIndex: 86, followingIndex: 88 },
    { followerIndex: 87, followingIndex: 85 }, { followerIndex: 87, followingIndex: 89 },
    { followerIndex: 88, followingIndex: 86 }, { followerIndex: 88, followingIndex: 90 },
    { followerIndex: 89, followingIndex: 87 }, { followerIndex: 89, followingIndex: 91 },
    { followerIndex: 90, followingIndex: 88 }, { followerIndex: 90, followingIndex: 92 },
    { followerIndex: 91, followingIndex: 89 }, { followerIndex: 91, followingIndex: 93 },
    { followerIndex: 92, followingIndex: 90 }, { followerIndex: 92, followingIndex: 94 },
    { followerIndex: 93, followingIndex: 91 }, { followerIndex: 93, followingIndex: 95 },
    { followerIndex: 94, followingIndex: 92 }, { followerIndex: 94, followingIndex: 96 },
    { followerIndex: 95, followingIndex: 93 }, { followerIndex: 95, followingIndex: 97 },
    { followerIndex: 96, followingIndex: 94 }, { followerIndex: 96, followingIndex: 98 },
    { followerIndex: 97, followingIndex: 95 }, { followerIndex: 97, followingIndex: 99 },
    { followerIndex: 98, followingIndex: 96 }, { followerIndex: 98, followingIndex: 0  },
    { followerIndex: 99, followingIndex: 97 }, { followerIndex: 99, followingIndex: 1  },
  ];

  for (const def of followDefs) {
    await prisma.follow.create({
      data: {
        createdAt:   new Date(Date.now() - Math.floor(Math.random() * 86400000 * 400)),
        followerId:  users[def.followerIndex].id,
        followingId: users[def.followingIndex].id,
      },
    });
  }
  console.log(`Created ${followDefs.length} follows.`);

  console.log("\nDone! Database seeded successfully.");
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
  });
